[2024-05-25T15:48:23.201+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-25T15:48:23.220+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: twitter_etl.get_twitter_data scheduled__2024-05-25T12:00:00+00:00 [queued]>
[2024-05-25T15:48:23.227+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: twitter_etl.get_twitter_data scheduled__2024-05-25T12:00:00+00:00 [queued]>
[2024-05-25T15:48:23.228+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-25T15:48:23.240+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): get_twitter_data> on 2024-05-25 12:00:00+00:00
[2024-05-25T15:48:23.246+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=225) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-25T15:48:23.247+0000] {standard_task_runner.py:63} INFO - Started process 226 to run task
[2024-05-25T15:48:23.247+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'twitter_etl', 'get_twitter_data', 'scheduled__2024-05-25T12:00:00+00:00', '--job-id', '157', '--raw', '--subdir', 'DAGS_FOLDER/csv_copy_to_mino_dag.py', '--cfg-path', '/tmp/tmpesc65bpj']
[2024-05-25T15:48:23.248+0000] {standard_task_runner.py:91} INFO - Job 157: Subtask get_twitter_data
[2024-05-25T15:48:23.291+0000] {task_command.py:426} INFO - Running <TaskInstance: twitter_etl.get_twitter_data scheduled__2024-05-25T12:00:00+00:00 [running]> on host fd6401a86447
[2024-05-25T15:48:23.355+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='twitter_etl' AIRFLOW_CTX_TASK_ID='get_twitter_data' AIRFLOW_CTX_EXECUTION_DATE='2024-05-25T12:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-25T12:00:00+00:00'
[2024-05-25T15:48:23.356+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-25T15:48:23.835+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-25T15:48:23.843+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/csv_copy_to_mino_dag.py", line 21, in get_twitter_data
    data = response["data"]
           ~~~~~~~~^^^^^^^^
KeyError: 'data'
[2024-05-25T15:48:23.851+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=twitter_etl, task_id=get_twitter_data, run_id=scheduled__2024-05-25T12:00:00+00:00, execution_date=20240525T120000, start_date=20240525T154823, end_date=20240525T154823
[2024-05-25T15:48:23.862+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 157 for task get_twitter_data ('data'; 226)
[2024-05-25T15:48:23.903+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-25T15:48:23.919+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-25T15:48:23.922+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
