[2024-05-23T15:55:35.414+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-23T15:55:35.432+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: csv_copy_dag.copy_csv manual__2024-05-23T15:55:34.493501+00:00 [queued]>
[2024-05-23T15:55:35.440+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: csv_copy_dag.copy_csv manual__2024-05-23T15:55:34.493501+00:00 [queued]>
[2024-05-23T15:55:35.441+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-05-23T15:55:35.455+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): copy_csv> on 2024-05-23 15:55:34.493501+00:00
[2024-05-23T15:55:35.461+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=147) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-23T15:55:35.463+0000] {standard_task_runner.py:63} INFO - Started process 148 to run task
[2024-05-23T15:55:35.462+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'csv_copy_dag', 'copy_csv', 'manual__2024-05-23T15:55:34.493501+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/csv_copy_dag.py', '--cfg-path', '/tmp/tmpyh_s5zcj']
[2024-05-23T15:55:35.464+0000] {standard_task_runner.py:91} INFO - Job 20: Subtask copy_csv
[2024-05-23T15:55:35.505+0000] {task_command.py:426} INFO - Running <TaskInstance: csv_copy_dag.copy_csv manual__2024-05-23T15:55:34.493501+00:00 [running]> on host df3735af794a
[2024-05-23T15:55:35.573+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='csv_copy_dag' AIRFLOW_CTX_TASK_ID='copy_csv' AIRFLOW_CTX_EXECUTION_DATE='2024-05-23T15:55:34.493501+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-23T15:55:34.493501+00:00'
[2024-05-23T15:55:35.574+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-23T15:55:35.590+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-23T15:55:35.590+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/csv_copy_dag.py", line 31, in copy_csv_file
    shutil.copy(src, dest)
  File "/usr/local/lib/python3.12/shutil.py", line 435, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/local/lib/python3.12/shutil.py", line 260, in copyfile
    with open(src, 'rb') as fsrc:
         ^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dags/source/sample.csv'
[2024-05-23T15:55:35.601+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=csv_copy_dag, task_id=copy_csv, run_id=manual__2024-05-23T15:55:34.493501+00:00, execution_date=20240523T155534, start_date=20240523T155535, end_date=20240523T155535
[2024-05-23T15:55:35.611+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 20 for task copy_csv ([Errno 2] No such file or directory: '/opt/airflow/dags/source/sample.csv'; 148)
[2024-05-23T15:55:35.637+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-23T15:55:35.651+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-23T15:55:35.653+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
