[2024-05-23T16:03:32.865+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-23T16:03:32.883+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: csv_copy_dag.copy_csv manual__2024-05-23T15:52:06.525983+00:00 [queued]>
[2024-05-23T16:03:32.890+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: csv_copy_dag.copy_csv manual__2024-05-23T15:52:06.525983+00:00 [queued]>
[2024-05-23T16:03:32.891+0000] {taskinstance.py:2306} INFO - Starting attempt 4 of 4
[2024-05-23T16:03:32.902+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): copy_csv> on 2024-05-23 15:52:06.525983+00:00
[2024-05-23T16:03:32.907+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=284) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-23T16:03:32.909+0000] {standard_task_runner.py:63} INFO - Started process 285 to run task
[2024-05-23T16:03:32.909+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'csv_copy_dag', 'copy_csv', 'manual__2024-05-23T15:52:06.525983+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/csv_copy_dag.py', '--cfg-path', '/tmp/tmp4cj44d43']
[2024-05-23T16:03:32.910+0000] {standard_task_runner.py:91} INFO - Job 35: Subtask copy_csv
[2024-05-23T16:03:32.955+0000] {task_command.py:426} INFO - Running <TaskInstance: csv_copy_dag.copy_csv manual__2024-05-23T15:52:06.525983+00:00 [running]> on host df3735af794a
[2024-05-23T16:03:33.030+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='csv_copy_dag' AIRFLOW_CTX_TASK_ID='copy_csv' AIRFLOW_CTX_EXECUTION_DATE='2024-05-23T15:52:06.525983+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-23T15:52:06.525983+00:00'
[2024-05-23T16:03:33.031+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-23T16:03:33.046+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-23T16:03:33.047+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/csv_copy_dag.py", line 31, in copy_csv_file
    shutil.copy(src, dest)
  File "/usr/local/lib/python3.12/shutil.py", line 435, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/local/lib/python3.12/shutil.py", line 260, in copyfile
    with open(src, 'rb') as fsrc:
         ^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dags/source/sample.csv'
[2024-05-23T16:03:33.057+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=csv_copy_dag, task_id=copy_csv, run_id=manual__2024-05-23T15:52:06.525983+00:00, execution_date=20240523T155206, start_date=20240523T160332, end_date=20240523T160333
[2024-05-23T16:03:33.066+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 35 for task copy_csv ([Errno 2] No such file or directory: '/opt/airflow/dags/source/sample.csv'; 285)
[2024-05-23T16:03:33.083+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-23T16:03:33.100+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-23T16:03:33.102+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
