[2024-05-25T14:16:22.434+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-25T14:16:22.449+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: csv_copy_to_minio_dag.copy_csv_to_minio manual__2024-05-25T14:16:15.124660+00:00 [queued]>
[2024-05-25T14:16:22.456+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: csv_copy_to_minio_dag.copy_csv_to_minio manual__2024-05-25T14:16:15.124660+00:00 [queued]>
[2024-05-25T14:16:22.457+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-05-25T14:16:22.471+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): copy_csv_to_minio> on 2024-05-25 14:16:15.124660+00:00
[2024-05-25T14:16:22.477+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=467) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-25T14:16:22.478+0000] {standard_task_runner.py:63} INFO - Started process 468 to run task
[2024-05-25T14:16:22.478+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'csv_copy_to_minio_dag', 'copy_csv_to_minio', 'manual__2024-05-25T14:16:15.124660+00:00', '--job-id', '78', '--raw', '--subdir', 'DAGS_FOLDER/csv_copy_to_mino_dag.py', '--cfg-path', '/tmp/tmpkq_a530o']
[2024-05-25T14:16:22.479+0000] {standard_task_runner.py:91} INFO - Job 78: Subtask copy_csv_to_minio
[2024-05-25T14:16:22.520+0000] {task_command.py:426} INFO - Running <TaskInstance: csv_copy_to_minio_dag.copy_csv_to_minio manual__2024-05-25T14:16:15.124660+00:00 [running]> on host 59b9dd79a01c
[2024-05-25T14:16:22.590+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='csv_copy_to_minio_dag' AIRFLOW_CTX_TASK_ID='copy_csv_to_minio' AIRFLOW_CTX_EXECUTION_DATE='2024-05-25T14:16:15.124660+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-25T14:16:15.124660+00:00'
[2024-05-25T14:16:22.591+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-25T14:16:22.612+0000] {base.py:84} INFO - Using connection ID 'minio_s3' for task execution.
[2024-05-25T14:16:22.613+0000] {connection_wrapper.py:387} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from extra.
[2024-05-25T14:16:22.613+0000] {warnings.py:110} WARNING - <string>:9: AirflowProviderDeprecationWarning: extra['host'] is deprecated and will be removed in a future release. Please set extra['endpoint_url'] instead

[2024-05-25T14:16:22.848+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-25T14:16:22.848+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/csv_copy_to_mino_dag.py", line 39, in copy_csv_to_minio
    found = s3_hook.check_for_bucket(bucket_name)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 89, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 288, in check_for_bucket
    self.get_conn().head_bucket(Bucket=bucket_name)
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/client.py", line 553, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/client.py", line 946, in _make_api_call
    api_params = self._emit_api_params(
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/client.py", line 1072, in _emit_api_params
    self.meta.events.emit(
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/hooks.py", line 412, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/hooks.py", line 256, in emit
    return self._emit(event_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/hooks.py", line 239, in _emit
    response = handler(**kwargs)
               ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/handlers.py", line 282, in validate_bucket_name
    if not VALID_BUCKET.search(bucket) and not VALID_S3_ARN.search(bucket):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: expected string or bytes-like object, got 'NoneType'
[2024-05-25T14:16:22.859+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=csv_copy_to_minio_dag, task_id=copy_csv_to_minio, run_id=manual__2024-05-25T14:16:15.124660+00:00, execution_date=20240525T141615, start_date=20240525T141622, end_date=20240525T141622
[2024-05-25T14:16:22.875+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 78 for task copy_csv_to_minio (expected string or bytes-like object, got 'NoneType'; 468)
[2024-05-25T14:16:22.893+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-25T14:16:22.907+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-25T14:16:22.909+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
