[2024-05-25T15:41:14.934+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-25T15:41:14.953+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: minio_etl.upload_csv_to_minio manual__2024-05-25T15:41:14.448239+00:00 [queued]>
[2024-05-25T15:41:14.961+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: minio_etl.upload_csv_to_minio manual__2024-05-25T15:41:14.448239+00:00 [queued]>
[2024-05-25T15:41:14.962+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-25T15:41:14.974+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): upload_csv_to_minio> on 2024-05-25 15:41:14.448239+00:00
[2024-05-25T15:41:14.979+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=130) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-25T15:41:14.980+0000] {standard_task_runner.py:63} INFO - Started process 131 to run task
[2024-05-25T15:41:14.980+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'minio_etl', 'upload_csv_to_minio', 'manual__2024-05-25T15:41:14.448239+00:00', '--job-id', '154', '--raw', '--subdir', 'DAGS_FOLDER/csv_copy_to_mino_dag.py', '--cfg-path', '/tmp/tmp3odbx6pw']
[2024-05-25T15:41:14.981+0000] {standard_task_runner.py:91} INFO - Job 154: Subtask upload_csv_to_minio
[2024-05-25T15:41:15.018+0000] {task_command.py:426} INFO - Running <TaskInstance: minio_etl.upload_csv_to_minio manual__2024-05-25T15:41:14.448239+00:00 [running]> on host fd6401a86447
[2024-05-25T15:41:15.083+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='minio_etl' AIRFLOW_CTX_TASK_ID='upload_csv_to_minio' AIRFLOW_CTX_EXECUTION_DATE='2024-05-25T15:41:14.448239+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-25T15:41:14.448239+00:00'
[2024-05-25T15:41:15.084+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-25T15:41:15.085+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-25T15:41:15.086+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/csv_copy_to_mino_dag.py", line 8, in upload_csv_to_minio
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-05-25T15:41:15.095+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=minio_etl, task_id=upload_csv_to_minio, run_id=manual__2024-05-25T15:41:14.448239+00:00, execution_date=20240525T154114, start_date=20240525T154114, end_date=20240525T154115
[2024-05-25T15:41:15.104+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 154 for task upload_csv_to_minio (No module named 'minio'; 131)
[2024-05-25T15:41:15.114+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-25T15:41:15.127+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-25T15:41:15.129+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
