[2024-05-25T14:28:48.255+0000] {processor.py:161} INFO - Started process (PID=136) to work on /opt/airflow/dags/destination/dump_data_to_bucker.py
[2024-05-25T14:28:48.256+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/destination/dump_data_to_bucker.py for tasks to queue
[2024-05-25T14:28:48.257+0000] {logging_mixin.py:188} INFO - [2024-05-25T14:28:48.256+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/destination/dump_data_to_bucker.py
[2024-05-25T14:28:48.657+0000] {logging_mixin.py:188} INFO - [2024-05-25T14:28:48.652+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/destination/dump_data_to_bucker.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/destination/dump_data_to_bucker.py", line 5, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-05-25T14:28:48.661+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/destination/dump_data_to_bucker.py
[2024-05-25T14:28:48.681+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/destination/dump_data_to_bucker.py took 0.431 seconds
[2024-05-25T14:29:18.810+0000] {processor.py:161} INFO - Started process (PID=148) to work on /opt/airflow/dags/destination/dump_data_to_bucker.py
[2024-05-25T14:29:18.811+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/destination/dump_data_to_bucker.py for tasks to queue
[2024-05-25T14:29:18.811+0000] {logging_mixin.py:188} INFO - [2024-05-25T14:29:18.811+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/destination/dump_data_to_bucker.py
[2024-05-25T14:29:19.155+0000] {logging_mixin.py:188} INFO - [2024-05-25T14:29:19.151+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/destination/dump_data_to_bucker.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/destination/dump_data_to_bucker.py", line 5, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-05-25T14:29:19.156+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/destination/dump_data_to_bucker.py
[2024-05-25T14:29:19.173+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/destination/dump_data_to_bucker.py took 0.367 seconds
[2024-05-25T14:30:02.174+0000] {processor.py:161} INFO - Started process (PID=43) to work on /opt/airflow/dags/destination/dump_data_to_bucker.py
[2024-05-25T14:30:02.175+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/destination/dump_data_to_bucker.py for tasks to queue
[2024-05-25T14:30:02.180+0000] {logging_mixin.py:188} INFO - [2024-05-25T14:30:02.180+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/destination/dump_data_to_bucker.py
[2024-05-25T14:30:02.671+0000] {logging_mixin.py:188} INFO - [2024-05-25T14:30:02.667+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/destination/dump_data_to_bucker.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/destination/dump_data_to_bucker.py", line 5, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-05-25T14:30:02.673+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/destination/dump_data_to_bucker.py
[2024-05-25T14:30:02.689+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/destination/dump_data_to_bucker.py took 0.520 seconds
[2024-05-25T14:30:32.941+0000] {processor.py:161} INFO - Started process (PID=55) to work on /opt/airflow/dags/destination/dump_data_to_bucker.py
[2024-05-25T14:30:32.942+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/destination/dump_data_to_bucker.py for tasks to queue
[2024-05-25T14:30:32.943+0000] {logging_mixin.py:188} INFO - [2024-05-25T14:30:32.943+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/destination/dump_data_to_bucker.py
[2024-05-25T14:30:33.356+0000] {logging_mixin.py:188} INFO - [2024-05-25T14:30:33.353+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/destination/dump_data_to_bucker.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/destination/dump_data_to_bucker.py", line 5, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-05-25T14:30:33.358+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/destination/dump_data_to_bucker.py
[2024-05-25T14:30:33.372+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/destination/dump_data_to_bucker.py took 0.436 seconds
[2024-05-25T14:31:03.527+0000] {processor.py:161} INFO - Started process (PID=66) to work on /opt/airflow/dags/destination/dump_data_to_bucker.py
[2024-05-25T14:31:03.528+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/destination/dump_data_to_bucker.py for tasks to queue
[2024-05-25T14:31:03.530+0000] {logging_mixin.py:188} INFO - [2024-05-25T14:31:03.529+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/destination/dump_data_to_bucker.py
[2024-05-25T14:31:03.911+0000] {logging_mixin.py:188} INFO - [2024-05-25T14:31:03.904+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/destination/dump_data_to_bucker.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/destination/dump_data_to_bucker.py", line 5, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-05-25T14:31:03.912+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/destination/dump_data_to_bucker.py
[2024-05-25T14:31:03.925+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/destination/dump_data_to_bucker.py took 0.403 seconds
[2024-05-25T14:31:34.062+0000] {processor.py:161} INFO - Started process (PID=77) to work on /opt/airflow/dags/destination/dump_data_to_bucker.py
[2024-05-25T14:31:34.063+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/destination/dump_data_to_bucker.py for tasks to queue
[2024-05-25T14:31:34.065+0000] {logging_mixin.py:188} INFO - [2024-05-25T14:31:34.064+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/destination/dump_data_to_bucker.py
[2024-05-25T14:31:34.463+0000] {logging_mixin.py:188} INFO - [2024-05-25T14:31:34.457+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/destination/dump_data_to_bucker.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/destination/dump_data_to_bucker.py", line 5, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-05-25T14:31:34.465+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/destination/dump_data_to_bucker.py
[2024-05-25T14:31:34.481+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/destination/dump_data_to_bucker.py took 0.426 seconds
[2024-05-25T14:32:04.709+0000] {processor.py:161} INFO - Started process (PID=88) to work on /opt/airflow/dags/destination/dump_data_to_bucker.py
[2024-05-25T14:32:04.709+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/destination/dump_data_to_bucker.py for tasks to queue
[2024-05-25T14:32:04.711+0000] {logging_mixin.py:188} INFO - [2024-05-25T14:32:04.710+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/destination/dump_data_to_bucker.py
[2024-05-25T14:32:05.120+0000] {logging_mixin.py:188} INFO - [2024-05-25T14:32:05.116+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/destination/dump_data_to_bucker.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/destination/dump_data_to_bucker.py", line 5, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-05-25T14:32:05.121+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/destination/dump_data_to_bucker.py
[2024-05-25T14:32:05.134+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/destination/dump_data_to_bucker.py took 0.430 seconds
[2024-05-25T14:32:35.379+0000] {processor.py:161} INFO - Started process (PID=100) to work on /opt/airflow/dags/destination/dump_data_to_bucker.py
[2024-05-25T14:32:35.380+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/destination/dump_data_to_bucker.py for tasks to queue
[2024-05-25T14:32:35.381+0000] {logging_mixin.py:188} INFO - [2024-05-25T14:32:35.381+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/destination/dump_data_to_bucker.py
[2024-05-25T14:32:35.781+0000] {logging_mixin.py:188} INFO - [2024-05-25T14:32:35.773+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/destination/dump_data_to_bucker.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/destination/dump_data_to_bucker.py", line 5, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-05-25T14:32:35.786+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/destination/dump_data_to_bucker.py
[2024-05-25T14:32:35.805+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/destination/dump_data_to_bucker.py took 0.429 seconds
[2024-05-25T14:33:07.774+0000] {processor.py:161} INFO - Started process (PID=43) to work on /opt/airflow/dags/destination/dump_data_to_bucker.py
[2024-05-25T14:33:07.775+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/destination/dump_data_to_bucker.py for tasks to queue
[2024-05-25T14:33:07.778+0000] {logging_mixin.py:188} INFO - [2024-05-25T14:33:07.778+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/destination/dump_data_to_bucker.py
[2024-05-25T14:33:08.488+0000] {logging_mixin.py:188} INFO - [2024-05-25T14:33:08.481+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/destination/dump_data_to_bucker.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/destination/dump_data_to_bucker.py", line 5, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-05-25T14:33:08.491+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/destination/dump_data_to_bucker.py
[2024-05-25T14:33:08.512+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/destination/dump_data_to_bucker.py took 0.743 seconds
[2024-05-25T14:34:21.204+0000] {processor.py:161} INFO - Started process (PID=43) to work on /opt/airflow/dags/destination/dump_data_to_bucker.py
[2024-05-25T14:34:21.205+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/destination/dump_data_to_bucker.py for tasks to queue
[2024-05-25T14:34:21.207+0000] {logging_mixin.py:188} INFO - [2024-05-25T14:34:21.206+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/destination/dump_data_to_bucker.py
[2024-05-25T14:34:23.026+0000] {logging_mixin.py:188} INFO - [2024-05-25T14:34:23.021+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/destination/dump_data_to_bucker.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/destination/dump_data_to_bucker.py", line 5, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-05-25T14:34:23.029+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/destination/dump_data_to_bucker.py
[2024-05-25T14:34:23.054+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/destination/dump_data_to_bucker.py took 1.854 seconds
[2024-05-25T14:34:53.127+0000] {processor.py:161} INFO - Started process (PID=54) to work on /opt/airflow/dags/destination/dump_data_to_bucker.py
[2024-05-25T14:34:53.128+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/destination/dump_data_to_bucker.py for tasks to queue
[2024-05-25T14:34:53.130+0000] {logging_mixin.py:188} INFO - [2024-05-25T14:34:53.130+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/destination/dump_data_to_bucker.py
[2024-05-25T14:34:53.394+0000] {logging_mixin.py:188} INFO - [2024-05-25T14:34:53.389+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/destination/dump_data_to_bucker.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/destination/dump_data_to_bucker.py", line 5, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-05-25T14:34:53.396+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/destination/dump_data_to_bucker.py
[2024-05-25T14:34:53.410+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/destination/dump_data_to_bucker.py took 0.288 seconds
